version: "3.9"
services:
  db:
    image: postgres:15
    container_name: lesson_db
    restart: always
    environment:
      POSTGRES_DB: cadventure_lessons
      POSTGRES_USER: cadventure
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  lesson-service:
    build: .
    container_name: lesson_service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cadventure_lessons
      SPRING_DATASOURCE_USERNAME: cadventure
      SPRING_DATASOURCE_PASSWORD: secret123
    depends_on:
      - db

volumes:
  pgdata:
